# Generated by Django 5.1.7 on 2025-04-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('faculty', models.CharField(max_length=200, verbose_name='Facultad')),
                ('university', models.CharField(max_length=200, verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Magíster',
                'verbose_name_plural': 'Magísteres',
                'ordering': ['name'],
            },
        ),
    ]
