# Generated by Django 5.2 on 2025-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='proceso_grado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15, verbose_name='Proceso de Grado'),
        ),
    ]
