# Generated by Django 5.1.7 on 2025-04-02 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0002_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe contener solo números, sin puntos ni guión.', regex='^\\d{1,13}$')], verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('correo_institucional', models.EmailField(max_length=254, verbose_name='Correo Institucional')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, verbose_name='Correo Personal')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inhabilitado', 'Inhabilitado'), ('retirado', 'Retirado')], default='activo', max_length=15, verbose_name='Estado')),
                ('proceso_grado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15, verbose_name='Proceso de Grado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gspg.intake', verbose_name='Intake')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
