# Generated by Django 5.1.7 on 2025-04-02 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0003_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe contener solo números, sin puntos ni guión.', regex='^\\d{1,13}$')], verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional')),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('magisteres', models.ManyToManyField(related_name='profesores', to='gspg.magister', verbose_name='Magísteres')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre'],
            },
        ),
    ]
