# Generated by Django 5.2 on 2025-04-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0003_alter_estudiante_proceso_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniongrupo',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='gspg.grupotrabajo', verbose_name='Grupo de Trabajo'),
        ),
    ]
