# Generated by Django 5.2 on 2025-04-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0004_reuniongrupo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniongrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='gspg.grupotrabajo', verbose_name='Grupo de Trabajo'),
        ),
    ]
