# Generated by Django 5.1.7 on 2025-04-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0004_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='proceso_grado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15, verbose_name='Proceso de Grado'),
        ),
    ]
