# Generated by Django 5.2 on 2025-04-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0005_alter_reuniongrupo_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='actas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='gspg.reuniongrupo')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gspg.profesor')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
