# Generated by Django 5.1.7 on 2025-04-02 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0005_alter_estudiante_proceso_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Proceso Finalizado')),
                ('estudiantes', models.ManyToManyField(related_name='grupos_trabajo', to='gspg.estudiante', verbose_name='Estudiantes')),
                ('magister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_trabajo', to='gspg.magister', verbose_name='Magíster')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_trabajo', to='gspg.profesor', verbose_name='Profesor Guía')),
            ],
            options={
                'verbose_name': 'Grupo de Trabajo',
                'verbose_name_plural': 'Grupos de Trabajo',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
