# Generated by Django 5.2 on 2025-04-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0006_actareunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gspg.persona')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gspg.reuniongrupo')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
