# Generated by Django 5.1.7 on 2025-04-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0006_grupotrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
