# Generated by Django 5.1.7 on 2025-04-03 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0007_alter_estudiante_telefono_alter_profesor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupotrabajo',
            name='intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_trabajo', to='gspg.intake', verbose_name='Intake'),
        ),
    ]
