# Generated by Django 5.2 on 2025-04-21 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0007_comentarioreunion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioreunion',
            name='autor',
        ),
        migrations.AddField(
            model_name='comentarioreunion',
            name='autor_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gspg.persona'),
        ),
        migrations.AddField(
            model_name='comentarioreunion',
            name='autor_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gspg.profesor'),
        ),
    ]
