# Generated by Django 5.1.7 on 2025-04-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0009_alter_grupotrabajo_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reunión')),
                ('hora', models.TimeField(verbose_name='Hora de Reunión')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20, verbose_name='Estado')),
                ('link_reunion', models.URLField(blank=True, help_text='URL para reunión virtual (opcional)', null=True, verbose_name='Link de Reunión')),
                ('comentario', models.TextField(blank=True, help_text='Notas adicionales sobre la reunión', verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='gspg.grupotrabajo', verbose_name='Grupo de Trabajo')),
            ],
            options={
                'verbose_name': 'Reunión de Grupo',
                'verbose_name_plural': 'Reuniones de Grupo',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
