# Generated by Django 5.1.7 on 2025-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0010_reuniongrupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magister',
            options={'ordering': ['name'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
    ]
