# Generated by Django 5.1.7 on 2025-04-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspg', '0011_alter_magister_options'),
        ('users', '0002_customuser_magister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='magister',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_magister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='gspg.magister', verbose_name='magister activo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='magisteres',
            field=models.ManyToManyField(blank=True, related_name='users', to='gspg.magister', verbose_name='magisteres'),
        ),
    ]
