# Generated by Django 5.2 on 2025-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_normalizado', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_universidades/')),
                ('color_primario', models.CharField(default='#1e40af', max_length=7)),
                ('color_secundario', models.CharField(default='#3b82f6', max_length=7)),
            ],
        ),
    ]
